//class for character Vulture
class Vulture{
    constructor(x,y,size,images){
		this.x=x
		this.y=y
		this.size=size
		this.images=images
		this.direction=0
		this.currentFrame=0
		this.hp=5
		this.maxHP=5
		this.vulture=[
			[this.images[0],this.images[12]],
			[this.images[1],this.images[13]],
			[this.images[2],this.images[14]],
			[this.images[3],this.images[15]],
			[this.images[4],this.images[16]],
			[this.images[5],this.images[17]],
			[this.images[6],this.images[18]],
			[this.images[7],this.images[19]],
			[this.images[8],this.images[20]],
			[this.images[9],this.images[21]],
			[this.images[10],this.images[22]],
			[this.images[11],this.images[23]],
			
		]
    }
	moveRight(){
		if(this.x==640){
			if(this.y==560){
				this.x+=this.size
			}
			this.x=this.x
		}
		else{
			this.x+=this.size
		}
	}
	moveLeft(){
		if(this.x==80){
			this.x=this.x
		}
		else{
			this.x-=this.size
		}
	}
	moveUp(){
		if(this.y==80){
			this.y=this.y
		}
		else{
			this.y-=this.size
		}
	}
	moveDown(){
		if(this.y==640){
			this.y=this.y
		}
		else{
			this.y+=this.size
		}
	}
	animationSprite(){
		image(this.vulture[this.currentFrame][this.direction],this.x,this.y)
	}
	animate(){
		this.currentFrame+=1
		if(this.currentFrame>11){
			this.currentFrame=0
		}
	}
}